### ISSUE TITLE
Prototype Implementation - Stand up Embedded Jetty operating environment

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#160]
**Prototype Implementation - Stand up Embedded Jetty operating environment**

Includes OpenDCS Web Client, and OpenDCS API. Investigate how CWMS AAA fits into this operating environment.

**Comment by adamkorynta** [comment]
Prototype works with embedded jetty and within Tomcat. Closed with PR: https://github.com/opendcs/rest_api/pull/186/
