### ISSUE TITLE
Prototype Implementation - Update OpenDCS API for JSESSIONIDSSO Handling

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#162]
**Prototype Implementation - Update OpenDCS API for JSESSIONIDSSO Handling**

Refactor as needed for authorization abstraction.
Implement JSESSIONIDSSO authorization.

**Comment by adamkorynta** [comment]
Closed with: https://github.com/opendcs/rest_api/pull/186/

**Comment by adamkorynta** [comment]
UI updates were incoporated in PR: https://github.com/opendcs/rest_api/pull/197
