### ISSUE TITLE
Integration Testing - Jetty

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#163]
**Integration Testing - Jetty**

Integration testing CWMS AAA login and OpenDCS API Authorization on Jetty.

**Comment by adamkorynta** [comment]
Added some IntelliJ HTTP Client integration tests here: https://github.com/opendcs/rest_api/pull/186/files#diff-ba672d6d81d584419515d16bc6c5db9cb866debf0f6b24a5bac70c0a1b65b6ad
