### ISSUE TITLE
Integration Testing - Failure Cases 

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#165]
**Integration Testing - Failure Cases**

Integration testing OpenDCS API authorization failures when unauthenticated.

**Comment by adamkorynta** [comment]
Added some IntelliJ HTTP Client integration tests here: https://github.com/opendcs/rest_api/pull/186/files#diff-ba672d6d81d584419515d16bc6c5db9cb866debf0f6b24a5bac70c0a1b65b6ad

**Comment by adamkorynta** [comment]
yeah, I've got some RestAssured tests written, but am still working on getting the Tomcat server started up.
