### ISSUE TITLE
Repository Configuration: Dependency Management

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#22]
Dependency Management

**Comment by adamkorynta** [comment]
Splitting apart standalone Jetty dependencies from the war file dependencies in PR: https://github.com/opendcs/rest_api/pull/46

**Comment by adamkorynta** [comment]
Setting up separate deployments and artifacts for CWMS Oracle vs Postgresql will be handled under the issue: https://github.com/opendcs/rest_api/issues/5
