### ISSUE TITLE
Repository Configuration: Source code

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#23]
Organize repository source code in order to adhere to build tool standards. Should ensure that the structure is easily decipherable for new developers.

**Comment by adamkorynta** [comment]
Updating project configuration with the following PR's
https://github.com/opendcs/rest_api/pull/48
https://github.com/opendcs/rest_api/pull/47

**Comment by adamkorynta** [comment]
TODO: Resolve dashes vs underscore discrepancies
