### ISSUE TITLE
OWASP Zap Automation Investigation

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#39]
OWASP Zap Automation Investigation

**Comment by adamkorynta** [comment]
Added OWASP Zap report generate in GitHub Actions. An example can be found here: https://github.com/opendcs/rest_api/actions/runs/7597437443. The HTML report is attached as well as a brief Markdown summary in the GitHub Action job summary: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
