### ISSUE TITLE
Dependabot Investigation

### ISSUE THREAD

**Issue by dezidizon** [opendcs/rest_api#40]
Dependabot Investigation

**Comment by adamkorynta** [comment]
Added dependabot configuration in PR: https://github.com/opendcs/rest_api/pull/57

**Comment by MikeNeilson** [comment]
@adamkorynta FYI if you add text liked `Fixes #40` to the PR description, or preferably the comments the tied in projects will automatically have their status set; as well as closing the issues automatically when merged in.

**Comment by adamkorynta** [comment]
Yeah, I don't want the issues automatically merged in, especially for these devops pieces that I can't really test until they've been merged. I tried looking for a keyword or setting that doesn't auto-merge, but couldn't find anything.

**Comment by adamkorynta** [comment]
Would you recommend just reopening the ticket if it doesn't work in that case?
