### ISSUE TITLE
Remove insecure printStackTrace calls.

### ISSUE THREAD

**Issue by wjonassen** [opendcs/rest_api#96]
**Describe the bug**
There are several printStackTrace calls in the code.  Throwable.printStackTrace(...) prints a Throwable and its stack trace to System.Err (by default) which is not easily parseable and can expose sensitive information.

**To Reproduce**
You can see in the code that these problems exist.

**Expected behavior**
Instead of printstacktrace, use a logger to show the message.

**Comment by rma-psmorris** [comment]
Work on this issue being performed under USACE W912HQ23F0243 Task 5 has been completed. This issue will be kept open to track parallel development efforts.
